mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #    springboot???mapper xml?????:
    variables:
      archive-status-nomal: 1
      archive-status-deleted: 11
  mapper-locations: classpath*:/mapper/**/**.xml
  type-aliases-package: com.rapidboot.demo.domain

spring:
  datasource:
    druid:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      filters: stat v
      initial-size: 3
      max-active: 15
      max-wait: 5000
      min-evictable-idle-time-millis: 1800000
      min-idle: 3
      stat-view-servlet:
        reset-enable: false
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 90000
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:log4jdbc:mysql://localhost:3306/yoma?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
      validation-query: select 1
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.  css,*.ico,/druid/*'
        url-pattern: /*
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect